### ISSUE TITLE
Жирные цены

### ISSUE THREAD

**Issue by yupe** [Rukomoynikov/yupestore#10]
http://www.awesomescreenshot.com/image/420043/ff71ead38e85312342d1d9339898941b

**Comment by Rukomoynikov** [comment]
![screenshot at 21 20-33-30](https://cloud.githubusercontent.com/assets/294399/8807865/d1a19ed6-2fe7-11e5-95dc-782b559c1c1d.png)

Так в макете.

**Comment by yupe** [comment]
Макс, не очень я понял что ты хотел показать =(((

**Comment by Rukomoynikov** [comment]
Я хотел сказать что так задумал @Valarkar. Но убираю жирноту.
