### ISSUE TITLE
Съехали блоки на главной

### ISSUE THREAD

**Issue by ApexWire** [Rukomoynikov/yupestore#12]
![by98hipvpyy](https://cloud.githubusercontent.com/assets/2697129/8780263/8ed1aa2e-2f10-11e5-982e-5716cd39bded.png)

**Comment by Rukomoynikov** [comment]
Так, пусть и мне заметка. Чтобы выделить блоки, контет любой, используйте outline вместо border. Outline не влияет на размер блока.
