### ISSUE TITLE
Футер приклеить внизу сайта

### ISSUE THREAD

**Issue by ApexWire** [Rukomoynikov/yupestore#15]

**Comment by Rukomoynikov** [comment]
Это можно сделать, но я знаю только способы где необходима фиксированная высота footer'a, а так как это шаблон для CMS, хочется чтобы пользователи изменив контент (меню в footer) не должны были бы менять CSS.

**Comment by ApexWire** [comment]
Наверное да. Интересно что другие думают

**Comment by yupe** [comment]
Соглашусь с @Rukomoynikov
