### ISSUE TITLE
catalog.html

### ISSUE THREAD

**Issue by ApexWire** [Rukomoynikov/yupestore#16]
Меню слева:
- при открытии блока должна меняться стрелка.
- баг. выбор checkbox. при нажатии на любой checkbox выбирается всегла первый

**Comment by Rukomoynikov** [comment]
Про checkbox да, мне просто лениво было всем уникальный id прописывать, они же в backend будут автоматом генерится. Хотя сейчас что-нибудь придумаем, в jade есть циклы, их и использую для генерации уникальных id.

**Comment by yupe** [comment]
http://www.awesomescreenshot.com/image/425173/a398318baa05c8403ab839c0d3af2715
1 Нет слайдера с ценами и лишняя первая полоска.
2 При сворачивании и разворачивании блоков фильтра направление стрелки должно меняться.
3 Убрать жирность.
4 Не показан пагинатор.
