### ISSUE TITLE
korzina.html

### ISSUE THREAD

**Issue by ApexWire** [Rukomoynikov/yupestore#18]
- некрасивый checkbox
- "купон на скидку"
- список товаров. не хаватет крестика справа у каждого товара

**Comment by yupe** [comment]
Да, блок с купоном совсем иной, см https://yadi.sk/d/OzefZT0QhGhBH/Korzina.png

http://www.awesomescreenshot.com/image/425191/8322540f709fbea32833c8496701f342

**Comment by yupe** [comment]
Остальные баги @ApexWire тоже верны =)

**Comment by yupe** [comment]
Еще нету "+" и "-" для увеличения количества товара.
