### ISSUE TITLE
oformlenie-zakaza.html

### ISSUE THREAD

**Issue by ApexWire** [Rukomoynikov/yupestore#19]
- не красивый select выбора города
- не красивые inputs radio

**Comment by Rukomoynikov** [comment]
Покажи пожалуйста как у тебя?

![2015-07-21 20 39 26](https://cloud.githubusercontent.com/assets/294399/8808015/a8234c34-2fe8-11e5-881f-c83d68757f8e.png)

**Comment by ApexWire** [comment]
Вот так нарисовано:
![eahrl5qucvw](https://cloud.githubusercontent.com/assets/2697129/8808896/f3b02d8e-2fed-11e5-8361-dab75e3a8c2a.png)

Вот так выглядит на windows firefox:
![kr1d0btwcai](https://cloud.githubusercontent.com/assets/2697129/8808900/00459872-2fee-11e5-8102-5c1121c74b72.png)

Когда создавал задачу смотрел на ubuntu firefox. Завтра скину как выглядит

**Comment by Rukomoynikov** [comment]
ok, сделаю везде одинаково.

**Comment by yupe** [comment]
http://www.awesomescreenshot.com/image/425196/2a4b25dd87820f1f64f3d5645dc343f2 
Убунта хром.
