### ISSUE TITLE
Табы в карточке

### ISSUE THREAD

**Issue by yupe** [Rukomoynikov/yupestore#2]
http://www.awesomescreenshot.com/image/419600/fe6cf05a2a066dd9b0498d233d083756 (как на макете)

**Comment by Rukomoynikov** [comment]
Это без проблем, и я намеренно их сделал в центре. Мне кажется так правильнее, это ведь не только табы но и меню. Ну вобщем, ок.

**Comment by yupe** [comment]
Хм. А это мысль. Что думают @dark_cs @sabian и @mikspark ?

**Comment by sabian** [comment]
Оба варианта нормально смотрятся. Я бы только, наверное, увеличил расстояние между ними и сделал какое-нибудь действие при наведении.

**Comment by DarkCs** [comment]
в центре тоже красиво

**Comment by Rukomoynikov** [comment]
@sabian Действие при наведении - ok.

**Comment by Valarkar** [comment]
Андрей показал правильно. Табы лучше выровнять по левому краю.

**Comment by yupe** [comment]
@Rukomoynikov  @Valarkar - это тот, кто рисовал диз +)
