### ISSUE TITLE
Расстояние между плитками карточек

### ISSUE THREAD

**Issue by yupe** [Rukomoynikov/yupestore#22]
http://www.awesomescreenshot.com/image/425155/7b59a96720592f2df69259b5e3e224d2

Может расстояние немного уменьшить ? Чтобы при наведении рамка активной карточки разворачивалась как раз до следующей карточки. Сейчас еще остается небольшой зазор - показал на скриншоте.

**Comment by Rukomoynikov** [comment]
ok
