### ISSUE TITLE
Меню второго уровня не перекрывает иконки

### ISSUE THREAD

**Issue by sabian** [Rukomoynikov/yupestore#3]
![catalog_bug](https://cloud.githubusercontent.com/assets/434141/8775263/22038ac8-2eef-11e5-8c89-11ecafb8d54f.png)

**Comment by Valarkar** [comment]
Здесь не нужно делать отступ слева, а лучше сделать все по левому краю (как на макете). Категории и так выделены (bold), а меню будет восприниматься быстрее и лучше, когда выровнено по левому краю, чем зигзагом как у тебя в скриншоте.

**Comment by Rukomoynikov** [comment]
@Valarkar я думаю Андрей имеет виду, эти наклейки NEW, они действительно там с подложки остались.

**Comment by sabian** [comment]
Да, речь о значках "NEW"

**Comment by Valarkar** [comment]
Не спорю и про NEW я сразу понял. 
Просто на скриншоте еще есть ошибка, про нее и написал.
