### ISSUE TITLE
Стрелочки в карточках

### ISSUE THREAD

**Issue by yupe** [Rukomoynikov/yupestore#5]
Какие-то они жирные, нужно как вот тут https://yadi.sk/d/OzefZT0QhGhBH/Glavnaya_hover.png
Живьем вот тут http://webaleks.besaba.com/yupe-store/

http://www.awesomescreenshot.com/image/420013/0bfd1cfbf98a3a0b2bad3a70af137894

**Comment by Rukomoynikov** [comment]
![2015-07-20 18 08 38](https://cloud.githubusercontent.com/assets/294399/8779137/66eba510-2f0a-11e5-8ff5-44b894e7c7e8.png)
Тот момент когда не вставил no-repeat для фона и всё выглядит в стиле диско.
