### ISSUE TITLE
Разные состояния лейблов

### ISSUE THREAD

**Issue by yupe** [Rukomoynikov/yupestore#7]
Вот тут http://webaleks.besaba.com/yupe-store/ при наведении на карточки в первом ряду видны разные лейблы: серые, зеленые, красные и т.д.
В новой версии этого нет.

**Comment by yupe** [comment]
Я про - http://www.awesomescreenshot.com/image/421943/6b58a5d8b9adb974adba758e3f696e0b

**Comment by Rukomoynikov** [comment]
Сделал. 

Лейблы сделаны из svg, для управления цветом и формой используйте:

цвет: svg-grey, svg-red,svg-green
форма: svg-normal, svg-skewed
